# Generated by Django 3.1 on 2022-03-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_auto_20201117_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoasistencia',
            name='tipo',
            field=models.CharField(choices=[('dinero', 'Dinero'), ('comida', 'Comida'), ('material_construccion', 'Material para construccion')], default='dinero', max_length=25),
        ),
    ]
