# Generated by Django 3.1 on 2023-06-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0004_auto_20220506_0812'),
        ('programa', '0004_auto_20220504_1235'),
    ]

    operations = [
    ]
