# Generated by Django 3.1 on 2023-05-09 22:52

from django.db import migrations, models
import uuid


def migrar_datos_uuid(apps, schema):
    Persona = apps.get_model('persona', 'Persona')
    for persona in Persona.objects.all():
        persona.uuid = uuid.uuid4()
        persona.save()


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_uuid'),
    ]

    operations = [
        migrations.RunPython(migrar_datos_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='persona',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
